## Lab: Iris dataset classification using a Decision Tree

Is the Decision Tree model used for supervised or unsupervised classification? Explain your answer.

Decision Trees used for supervised classification as you label each record for training.

In [8]:
import pandas as pd
import numpy as np
import copy

In [9]:
dataset = pd.read_csv("Iris.csv", delimiter=',')

In [10]:
dataset.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

1. What is the nature of the attributes of the dataset?

The attributes represent the values of length.

2. Do you think it is necessary to transform the attributes (scaling, standardization, ...)?

For now I think we do not need it. Values are definitive and easy to compare.

3. How are you going to use real value attributes to build your Decision Tree?

In [11]:
dataset[dataset['Species'] == 'Iris-setosa']

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [15]:
def sort_species(dataset, specimen):
    return dataset[dataset['Species'] == specimen]

In [16]:
def entropy(dataset, instances):
    s = 0
    N = dataset.shape[0]
    for specimen in instances:
        n_specimen = sort_species(dataset, specimen).shape[0]
        s +=  n_specimen / N * np.log2(n_specimen / N)
    s *= -1
    return s

Dataset entropy : 1.584962500721156

In [18]:
# entropy for each group
# number of occurences (4 tables)

In [19]:
def separate_in_groups_by_attribute(dataset, N_groups=3):
    attributes = dataset.columns[1:-1]
    groups_by_attr = {}
    N = dataset.shape[0]
    for attribute in attributes:
        sorted_data = dataset.sort_values(attribute).loc[:, [attribute, 'Species']]
        groups = []
        for i in range(N_groups):
            groups.append(sorted_data[int(i*N/3):int((i+1)*N/3)])
        groups_by_attr[attribute] = groups
    return groups_by_attr

In [20]:
groups_by_attr = separate_in_groups_by_attribute(dataset)

In [33]:
tmp = groups_by_attr['SepalLengthCm'][0].groupby(['Species']).count()
tmp.loc['new', :] = 0
tmp = tmp.astype(np.int64)

                 SepalLengthCm
Species
Iris-setosa                 43
Iris-versicolor              6
Iris-virginica               1
new                          0

In [34]:
def count_by_species(df, species=['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']):
    counted_df = df.groupby(['Species']).count()
    for specimen in species:
        if not counted_df.index.isin([specimen]).any():
            counted_df.loc[specimen, :] = 0
            counted_df = counted_df.astype(np.int64)
    return counted_df

In [48]:
def count_groups_by_species(groups_by_attr):
    groups_by_species_counted = copy.deepcopy(groups_by_attr)
    for attr in groups_by_species_counted.keys():
        for group in range(len(groups_by_species_counted[attr])):
            groups_by_species_counted[attr][group] = count_by_species(groups_by_species_counted[attr][group])
    return groups_by_species_counted

In [49]:
groups_by_species_counted = copy.deepcopy(groups_by_attr)

In [50]:
groups_by_species_counted = count_groups_by_species(groups_by_attr)

In [51]:
def print_groups_by_species(groups):
    group_name = ['small', 'medium', 'large']
    for attr in groups.keys():
        print("Attribute: ", attr)
        for group in range(len(groups[attr])):
            print("\nGroup N{} ({})".format(group, group_name[group]))
            print(groups[attr][group], end='\n')
        print("-" * 100)

In [52]:
print_groups_by_species(groups_by_species_counted)

Attribute:  SepalLengthCm

Group N0 (small)
                 SepalLengthCm
Species
Iris-setosa                 43
Iris-versicolor              6
Iris-virginica               1

Group N1 (medium)
                 SepalLengthCm
Species
Iris-setosa                  7
Iris-versicolor             31
Iris-virginica              12

Group N2 (large)
                 SepalLengthCm
Species
Iris-versicolor             13
Iris-virginica              37
Iris-setosa                  0
----------------------------------------------------------------------------------------------------
Attribute:  SepalWidthCm

Group N0 (small)
                 SepalWidthCm
Species
Iris-setosa                 1
Iris-versicolor            30
Iris-virginica             19

Group N1 (medium)
                 SepalWidthCm
Species
Iris-setosa                13
Iris-versicolor            16
Iris-virginica             21

Group N2 (large)
                 SepalWidthCm
Species
Iris-setosa                36
Iris-versicolor             4
Iris-virginica             10
----------------------------------------------------------------------------------------------------
Attribute:  PetalLengthCm

Group N0 (small)
                 PetalLengthCm
Species
Iris-setosa                 50
Iris-versicolor              0
Iris-virginica               0

Group N1 (medium)
                 PetalLengthCm
Species
Iris-versicolor             47
Iris-virginica               3
Iris-setosa                  0

Group N2 (large)
                 PetalLengthCm
Species
Iris-versicolor              3
Iris-virginica              47
Iris-setosa                  0
----------------------------------------------------------------------------------------------------
Attribute:  PetalWidthCm

Group N0 (small)
                 PetalWidthCm
Species
Iris-setosa                50
Iris-versicolor             0
Iris-virginica              0

Group N1 (medium)
                 PetalWidthCm
Species
Iris-versicolor            46
Iris-virginica              4
Iris-setosa                 0

Group N2 (large)
                 PetalWidthCm
Species
Iris-versicolor             4
Iris-virginica             46
Iris-setosa                 0
----------------------------------------------------------------------------------------------------

In [ ]:
def entropy(dataset, instances):
    s = 0
    N = dataset.shape[0]
    for specimen in instances:
        n_specimen = sort_species(dataset, specimen).shape[0]
        s +=  n_specimen / N * np.log2(n_specimen / N)
    s *= -1
    return s

In [61]:
print("Dataset entropy : {}".format(entropy(dataset, dataset['Species'].unique())))

Dataset entropy : 1.584962500721156

In [63]:
entropy()

1.5849625007211563

In [112]:
def entropy_group(dataset, N=50):
    s = 0
    for specimen in dataset.index:
        n_specimen = dataset.loc[specimen, :][0]
        if n_specimen != 0:
            s += (n_specimen / N) * np.log2(n_specimen / N)
    s *= -1
    return s

In [113]:
dataset =  groups_by_species_counted['SepalLengthCm'][2]

In [116]:
group_name = ['small', 'medium', 'large']
attr_entropies = {}
for attr in groups_by_species_counted:
    groups = []
    for group in range(len(groups_by_species_counted[attr])):
        groups.append(entropy_group(groups_by_species_counted[attr][group]))
    attr_entropies[attr] = groups

In [117]:
group_name = ['small', 'medium', 'large']
for attr in attr_entropies:
    print(attr)
    for group in range(len(attr_entropies[attr])):
        print("{}".format(attr_entropies[attr][group]))
    print("-" * 50)

SepalLengthCm
0.6670730006443818
1.31883378807372
0.8267463724926178
--------------------------------------------------
SepalWidthCm
1.0855093773010511
1.5569685454909616
1.0971245697587872
--------------------------------------------------
PetalLengthCm
-0.0
0.32744491915447627
0.32744491915447627
--------------------------------------------------
PetalWidthCm
-0.0
0.4021791902022728
0.4021791902022728
--------------------------------------------------